services:

  postgres:

    image: postgres:15

    container_name: postgres_music

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: musicdb

    ports:

      - "54321:5432"

    volumes:

      - pgdata:/var/lib/postgresql/data
 
volumes:

  pgdata:
 